language: node_js
node_js:
- node
before_script:
- npm i
script:
- npm run lint
- npm test
- npm audit
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -oStrictHostKeyChecking=no $deploy_user@$deploy_url "deploy_commit_hash=$TRAVIS_COMMIT bash -ic ~/deploy.sh" >/dev/null 2>&1
  on:
    branch: master
